### PR TITLE
fix XSS serving 404 as text/plain

### PR DESCRIPTION
**Pull request by davitST**

### CODE REVIEW

**Comment by kanoshin** [comment]
@davitST tests are failing for this change. Could you also write up a summary of why these changes are required and how XSS is possible with text/html or application/json response headers.

**Comment by davitST** [comment]
When application fails to find a resource on npm, it reflects the request URI path decoding it, thus leading to XSS. However it is easy to fix having the content type as text/plain, so the browser won't render the html tags.I added `.type('text')` to `res` which makes the response content type "text/plain", instead of default "text/html" that is responded with `.send()`. application/json content type is actually not affected, and this PR is not changing any response that had such content type.
Latest published commit hasn't passed test as well, so I don't think they have anything to do with my changes. Let me know if you have any questions @kanoshin.

**Comment by davitST** [comment]
hey @kanoshin, can we merge this?

**Comment by kanoshin** [comment]
@davitST sorry for the delay. I'm pretty certain that part of the tests is failing because of this change. If you look into the failing tests [here](https://github.com/servicetitan/unpkg/actions/runs/5516070027/job/14933634053) it's just one test failing. In this PR [there are 3 failing tests](https://github.com/servicetitan/unpkg/actions/runs/5979393026/job/16223383226?pr=27) and 2 of those are related to a change in the response header.

**Comment by davitST** [comment]
hey @kanoshin, I updated tests to match what we expect, i.e. text/plain on  404s, thanks for highlighting those  !

**Review by kanoshin — APPROVED** [review]

**Pull request merged**
