### PR TITLE
FAR-1246: Add github action for running load test

### PR DESCRIPTION
**Pull request by seanmadi**
Edited `load-test.js` to accept environment variables for all possible variables. 
Then those env vars are passed in via the Github action.

Can test with the Github CLI
```
gh workflow run 81132103 --ref far-1246-gh-action -f stableDuration='1m'
```

https://servicetitan.atlassian.net/browse/FAR-1246

### CODE REVIEW

**Comment by seanmadi** [comment]
@kanoshin I need to change the Verdaccio auth token from an input to a repo secret. Can you give me access config for the repo (or add the secret, if I shouldn't have access)?

**Review by dextersealy — APPROVED** [review]

**Comment by kanoshin** [comment]
@seanmadi just added our team as Admin for this repo.

**Review by kanoshin — APPROVED** [review]
It looks good to me. But question is where are we going to run `npm publish` job? Since it's currently in uikit it's going to require checking out uikit repo to run as a separate job in this workflow. Should we move @dextersealy's [code](https://github.com/servicetitan/uikit/pull/1943) with simple npm package to this repo?

**Comment by dextersealy** [comment]
> It looks good to me. But question is where are we going to run `npm publish` job? Since it's currently in uikit it's going to require checking out uikit repo to run as a separate job in this workflow. Should we move @dextersealy's [code](https://github.com/servicetitan/uikit/pull/1943) with simple npm package to this repo?

Or, move `load-tests` to uikit? It's where we do most of our work and would be easier to new developers to find.

**Comment by kanoshin** [comment]
This sounds equally good to me. We can even move verdaccio docker container to uikit and keep this repo as unpkg fork only.

**Pull request merged**
